apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-api-tutorial
spec:
  selector:
    matchLabels:
      app: nestjs-api-tutorial
  replicas: 2
  template:
    metadata:
      labels:
        app: nestjs-api-tutorial
    spec:
      containers:
        - name: nestjs-api-tutorial
          image: laouni237/nestjs-k8s
          env:
            - name: POSTGRES_DB
              value: "nest"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "123123"
            - name: DATABASE_URL
              value: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5434/${POSTGRES_DB}?schema=public"
          ports:
            - containerPort: 5000
